### ISSUE TITLE
[Task] Filing app - Skeleton page (Phase 1 - mock data)

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#285]
- [x] Launch the filing platform - https://github.com/cfpb/sbl-project/issues/77
- [x] See list of active institutions I can file for - https://github.com/cfpb/sbl-project/issues/120 (Phase 1)
  - [x] See current Filing status of each institution - https://github.com/cfpb/sbl-project/issues/121 (Phase 1)
  - [x] Start the filing process for an associated institution - https://github.com/cfpb/sbl-project/issues/123 (Phase 1)
