### ISSUE TITLE
[Task] Filing app - Skeleton page (Phase 2 - live data)

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#286]
- [x] See list of active institutions I can file for - https://github.com/cfpb/sbl-project/issues/120 (Phase 2)
  - [x] See current Filing status of each institution - https://github.com/cfpb/sbl-project/issues/121 (Phase 2)
  - [x] Start the filing process for an associated institution - https://github.com/cfpb/sbl-project/issues/123 (Phase 2)

Notes
- [Filing API endpoints](https://github.com/cfpb/sbl-filing-api/wiki/Endpoints-%E2%80%90-Filings)
- [Sequence diagrams](https://github.com/cfpb/sbl-filing-api/issues/34)
