### ISSUE TITLE
[Styling Issues] Landing pages

### ISSUE THREAD

**Issue by meissadia** [cfpb/sbl-frontend#315]
## Issues
- Section content should all left-align and be aligned with each other
- Reference: https://www.consumerfinance.gov/consumer-tools/auto-loans/

## Pages
- [ ] Authenticated landing
- [ ] Unauthenticated landing

## Todo
- [ ] Review DSR components and verify their implementation aligns with DS
- [ ] Review SBL pages and verify their structure aligns with [CF Auto loans](https://www.consumerfinance.gov/consumer-tools/auto-loans/)
- [ ] Remove additional borders/padding/margins applied only in SBL
- [ ] Confirm content alignment

**Comment by billhimmelsbach** [comment]
I think this is completed, but maybe worth checking.

**Comment by natalia-fitzgerald** [comment]
@meissadia 
I don't think this is completed but I will add it to my list of things to check after I am able to review the responsive navigation.
